import java.util.ArrayList;

/**
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.
 */
public class FindtheDifference_389 {
    public char findTheDifference(String s, String t) {
//        char[] sa = s.toCharArray();
//        char[] ta = t.toCharArray();
//        for (int i = 0; i <sa.length ; i++) {
//
//        }
        int length = s.length();
        char k=0;
        for (int i = 0; i < length; i++) {
            k ^= s.charAt(i) ^ t.charAt(i);
        }
        return (char) (k^t.charAt(length));

//        for (int i = 0; i < t.length(); i++) {
//            if (list.contains(t.charAt(i))){
//                list.remove(new Character(t.charAt(i)));
//            }
//            else {
//                return t.charAt(i);
//            }
//        }
//        return list.get(0);
    }

    public static void main(String[] args) {
        System.out.println(new FindtheDifference_389().findTheDifference("abcd","abbcd"));
    }
}
